### ISSUE TITLE
Twitter registration not working

### ISSUE THREAD

**Issue by Mistermay** [cmextension/cmsocialconnect#5]
HI, 

When choosing for twitter the redirect url goes to:

/component/cmsocialconnect/?task=registration.socialRegister

This ends up in an error. Any ideas why this is?

**Comment by tranduyhung** [comment]
What error do you get?

**Comment by Mistermay** [comment]
Hi,


I see this error:




Op 10/01/2017 om 16:15 schreef Hung Tran:

**Comment by tranduyhung** [comment]
Could you please copy and paste the error? It seems your screenshot wasn't passed to Github. Thanks!

**Comment by Mistermay** [comment]
<img width="996" alt="img_7118" src="https://cloud.githubusercontent.com/assets/25034354/21839137/72a9134e-d7d6-11e6-9cf4-76a09ff2c9c4.PNG">

**Comment by tranduyhung** [comment]
The problem seems coming from your Twitter app. Could you please attach the screenshots of your Twitter app's current settings? You can blur any private information in  your screenshots. Thank you!

**Comment by Mistermay** [comment]
Ah made a typo ^^ sorry........ Very good extension btw. Simple and straight forward!
